### ISSUE TITLE
Doc Feedback: Michael Ieradi

### ISSUE THREAD

**Issue by mieradi** [ravendesignsystem/rds#29]
**General Overview**

The docs for **Understanding RDS** are very wordy, and a little confusing. I think it would be helpful to have very clear, concise examples alongside a visual representation, and the code to go with it. When I am reading docs I am generally looking for **what & why** as fast as possible. Ideally, I think it would be good to see a structured page using Layouts, Blocks, etc in the same format as the docs for Components or Blocks. 

Re: https://tailwindcss.com/docs/what-is-tailwind/

You get a general overview, intriguing visual example, and the code to go with it right away.

Also, the main overview would be helpful at the top of the page so users see it right away. 

**Page structure**

Like a lot of docs now, having the nav in a sidebar is an easy win. scrolling a big list of similar style headings is a little confusing for a new user. 

Loading the views via ajax would also be ideal. 2019 hates page reloads.

**Comment by dannybrown73** [comment]
A lot has changed since the early docs in April, including primary nav and secondary vertical nav, overall page structure, more code comments. There is still a lot to do but gonna close this one but add 'Loading the views via ajax would also be ideal. 2019 hates page reloads.' to the roadmap, as yeah that would be better.
