### ISSUE TITLE
Masthead 2.0 - issues with submenus on mobile

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#86]
On iPhone 10 - latest iOS

**Issue 1:**

The hover submenus are hidden by what looks to be an overflow hidden issue on tap.

![Screenshot 2019-10-29 at 5 59 26 AM](https://user-images.githubusercontent.com/2328234/67757459-3827d280-fa12-11e9-972b-165d2092080f.jpeg)

**Issue 2**

The click submenu does not display. It appears to be to far off to the right of the viewport.

![Screenshot 2019-10-29 at 6 00 09 AM](https://user-images.githubusercontent.com/2328234/67757532-5beb1880-fa12-11e9-8ee0-ca435cf51df0.jpeg)

<img width="368" alt="image" src="https://user-images.githubusercontent.com/2328234/67757275-dbc4b300-fa11-11e9-9535-2de29b922595.png">

Note on the screenshot above you can see it off to the right of the viewport.

**Comment by troychaplin** [comment]
@dannybrown73 i was looking at these issues yesterday, and I'm not quite sure what we can do with the current setup...

The overflow on tap thing also exists in master and can be recreated in the docs site right now. The problem with the menu attached to "Child Menu Example" has been there since the start as well, it also happens on desktop. This was something that you pointed out to me a while ago and it's because of the fixed positioning on the child nav.

**Comment by dannybrown73** [comment]
While it is in Master, I had all of this working at one point. I'm just not sure when it stopped. So I know it can work.

If you want me to take a look, I can.

**Comment by dannybrown73** [comment]
Closing, in lieuy of master issue
